[package]
name = "tsw"
version = "0.3.0-alpha.1"
edition = "2024"
authors = ["NTeditor <nteditor4@gmail.com>"]
description = "SU wrapper for termux"
license = "GPL-3.0-only"
repository = "https://github.com/nteditor/tsw"
readme = "README.md"

[dependencies]
anyhow = { version = "1.0.100", features = ["backtrace"] }
clap = { version = "4.5.48", features = ["derive"] }
env_logger = { version = "0.11.8", features = ["kv"] }
log = { version = "0.4.28", features = ["kv"] }
shlex = "1.3.0"
